<?php

if ( function_exists( 'acf_add_local_field_group' ) ):

	acf_add_local_field_group( array(
		'key'                   => 'group_576a39fa76a31',
		'title'                 => 'Historie',
		'fields'                => array(
			array(
				'default_value'     => '',
				'maxlength'         => '',
				'placeholder'       => '',
				'prepend'           => '',
				'append'            => '',
				'key'               => 'field_576a4d01dc2cf',
				'label'             => 'Überschrift',
				'name'              => 'history_headline',
				'type'              => 'text',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'readonly'          => 0,
				'disabled'          => 0,
			),
			array(
				'default_value'     => '',
				'maxlength'         => '',
				'placeholder'       => '',
				'prepend'           => '',
				'append'            => '',
				'key'               => 'field_576a509c3d758',
				'label'             => 'Subline',
				'name'              => 'history_subline',
				'type'              => 'text',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'readonly'          => 0,
				'disabled'          => 0,
			),
			array(
				'sub_fields'        => array(
					array(
						'default_value'     => '',
						'min'               => '',
						'max'               => '',
						'step'              => '',
						'placeholder'       => '',
						'prepend'           => '',
						'append'            => '',
						'key'               => 'field_576a4275da43a',
						'label'             => 'Datum',
						'name'              => 'date',
						'type'              => 'number',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'readonly'          => 0,
						'disabled'          => 0,
					),
					array(
						'default_value'     => '',
						'maxlength'         => '',
						'placeholder'       => '',
						'prepend'           => '',
						'append'            => '',
						'key'               => 'field_576a4295da43b',
						'label'             => 'Titel',
						'name'              => 'title',
						'type'              => 'text',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'readonly'          => 0,
						'disabled'          => 0,
					),
					array(
						'default_value'     => '',
						'new_lines'         => 'wpautop',
						'maxlength'         => '',
						'placeholder'       => '',
						'rows'              => '',
						'key'               => 'field_576a42a4da43c',
						'label'             => 'Beschreibung',
						'name'              => 'description',
						'type'              => 'textarea',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'readonly'          => 0,
						'disabled'          => 0,
					),
					array(
						'return_format'     => 'id',
						'preview_size'      => 'thumbnail',
						'library'           => 'all',
						'min_width'         => '',
						'min_height'        => '',
						'min_size'          => '',
						'max_width'         => '',
						'max_height'        => '',
						'max_size'          => '',
						'mime_types'        => '',
						'key'               => 'field_576a42c050aab',
						'label'             => 'Bild',
						'name'              => 'image',
						'type'              => 'image',
						'instructions'      => '',
						'required'          => '',
						'conditional_logic' => '',
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
					),
				),
				'min'               => 0,
				'max'               => 0,
				'layout'            => 'row',
				'button_label'      => 'Eintrag hinzufügen',
				'collapsed'         => '',
				'key'               => 'field_576a4266da439',
				'label'             => 'Events',
				'name'              => 'history_events',
				'type'              => 'repeater',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
			),
		),
		'location'              => array(
			array(
				array(
					'param'    => 'page_template',
					'operator' => '==',
					'value'    => '_templates/_template-history.php',
				),
			),
		),
		'menu_order'            => 0,
		'position'              => 'normal',
		'style'                 => 'default',
		'label_placement'       => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen'        => '',
		'active'                => 1,
		'description'           => '',
	) );

endif;