<?php

if ( function_exists( 'acf_add_local_field_group' ) ):

	acf_add_local_field_group( array(
		'key'                   => 'group_58bedb632f4e5',
		'title'                 => 'CPT: Veranstaltung',
		'fields'                => array(
			array(
				'key'               => 'field_58bedb7302edc',
				'label'             => 'Termine',
				'name'              => 'dates',
				'type'              => 'repeater',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'min'               => 1,
				'max'               => 0,
				'layout'            => 'table',
				'button_label'      => 'Termin hinzufügen',
				'collapsed'         => '',
				'sub_fields'        => array(
					array(
						'key'               => 'field_58bedb633e251',
						'label'             => 'Veranstaltungsbeginn',
						'name'              => 'event-start',
						'type'              => 'date_picker',
						'instructions'      => '',
						'required'          => 1,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'display_format'    => 'd.m.Y',
						'return_format'     => 'Ymd',
						'first_day'         => 1,
					),
					array(
						'key'               => 'field_58bedb633e2d7',
						'label'             => 'Veranstaltungsbeginn (Zeit)',
						'name'              => 'event-start-time',
						'type'              => 'time_picker',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'display_format'    => 'H:i',
						'return_format'     => 'H:i',
					),
					array(
						'key'               => 'field_58bedb633e35a',
						'label'             => 'Veranstaltungsende',
						'name'              => 'event-end',
						'type'              => 'date_picker',
						'instructions'      => '',
						'required'          => 1,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'display_format'    => 'd.m.Y',
						'return_format'     => 'Ymd',
						'first_day'         => 1,
					),
					array(
						'key'               => 'field_58bedb633e3dd',
						'label'             => 'Veranstaltungsende (Zeit)',
						'name'              => 'event-end-time',
						'type'              => 'time_picker',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'display_format'    => 'H:i',
						'return_format'     => 'H:i',
					),
				),
			),
			array(
				'key'               => 'field_58bedb633e45f',
				'label'             => 'Adresse, Hausnummer',
				'name'              => 'address',
				'type'              => 'text',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
				'maxlength'         => '',
				'placeholder'       => '',
				'prepend'           => '',
				'append'            => '',
			),
			array(
				'key'               => 'field_58bedb633e4e1',
				'label'             => 'Postleitzahl',
				'name'              => 'postal_code',
				'type'              => 'text',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
				'maxlength'         => '',
				'placeholder'       => '',
				'prepend'           => '',
				'append'            => '',
			),
			array(
				'key'               => 'field_58bedb633e564',
				'label'             => 'Stadt',
				'name'              => 'city',
				'type'              => 'text',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
				'maxlength'         => '',
				'placeholder'       => '',
				'prepend'           => '',
				'append'            => '',
			),
			array(
				'key'               => 'field_58bedb633e5e6',
				'label'             => 'Bundesland',
				'name'              => 'state',
				'type'              => 'text',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
				'maxlength'         => '',
				'placeholder'       => '',
				'prepend'           => '',
				'append'            => '',
			),
			array(
				'key'               => 'field_58bedb633e669',
				'label'             => 'Land',
				'name'              => 'country',
				'type'              => 'select',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'multiple'          => 0,
				'allow_null'        => 0,
				'choices'           => array(
					'Deutschland'   => 'Deutschland',
					'Österreich'    => 'Österreich',
					'Schweiz'       => 'Schweiz',
					'International' => 'International',
				),
				'default_value'     => array(),
				'ui'                => 0,
				'ajax'              => 0,
				'placeholder'       => '',
				'return_format'     => 'value',
			),
			array(
				'key'               => 'field_58bedb633e6eb',
				'label'             => 'Raum',
				'name'              => 'room',
				'type'              => 'text',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
				'maxlength'         => '',
				'placeholder'       => '',
				'prepend'           => '',
				'append'            => '',
			),
			array(
				'key'               => 'field_58bedb633e76d',
				'label'             => 'Ansprechpartner',
				'name'              => 'contact_person',
				'type'              => 'text',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
				'maxlength'         => '',
				'placeholder'       => '',
				'prepend'           => '',
				'append'            => '',
			),
			array(
				'key'               => 'field_58bedb633e7f0',
				'label'             => 'Land (international)',
				'name'              => 'event-country-international',
				'type'              => 'text',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => array(
					array(
						array(
							'field'    => 'field_58bedb633e669',
							'operator' => '==',
							'value'    => 'International',
						),
					),
				),
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
				'maxlength'         => '',
				'placeholder'       => '',
				'prepend'           => '',
				'append'            => '',
				'readonly'          => 0,
				'disabled'          => 0,
			),
			array(
				'key'               => 'field_58bedb633e872',
				'label'             => 'Veranstaltungs-Download',
				'name'              => 'event-download',
				'type'              => 'repeater',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'min'               => 0,
				'max'               => 0,
				'layout'            => 'table',
				'button_label'      => 'Add Row',
				'collapsed'         => '',
				'row_min'           => '',
				'row_limit'         => '',
				'sub_fields'        => array(
					array(
						'key'               => 'field_58bedb63750fc',
						'label'             => 'Titel des Downloads',
						'name'              => 'event-download-entry-title',
						'type'              => 'text',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'default_value'     => '',
						'maxlength'         => '',
						'placeholder'       => '',
						'prepend'           => '',
						'append'            => '',
						'formatting'        => 'html',
						'readonly'          => 0,
						'disabled'          => 0,
					),
					array(
						'key'               => 'field_58bedb6375182',
						'label'             => 'Dateidownload',
						'name'              => 'event-download-entry-file',
						'type'              => 'file',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'return_format'     => 'array',
						'library'           => 'all',
						'min_size'          => '',
						'max_size'          => '',
						'mime_types'        => '',
					),
				),
			),
			array(
				'key'               => 'field_58bee2598fcbf',
				'label'             => 'Anmeldeformular',
				'name'              => 'anmeldeformular',
				'type'              => 'cf7',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'allow_null'        => 1,
				'multiple'          => 0,
				'disable'           => '',
			),
		),
		'location'              => array(
			array(
				array(
					'param'    => 'post_type',
					'operator' => '==',
					'value'    => 'veranstaltung',
				),
			),
		),
		'menu_order'            => 0,
		'position'              => 'acf_after_title',
		'style'                 => 'default',
		'label_placement'       => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen'        => '',
		'active'                => 1,
		'description'           => '',
	) );

endif;