<?php

if ( function_exists( 'acf_add_local_field_group' ) ):

	acf_add_local_field_group( array(
		'key'                   => 'group_56deea94c6fdc',
		'title'                 => 'CPT: Stellenangebot',
		'fields'                => array(
			array(
				'placement'         => 'top',
				'endpoint'          => 0,
				'key'               => 'field_56deec36ac6c8',
				'label'             => 'Arbeitszeiten',
				'name'              => '',
				'type'              => 'tab',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
			),
			array(
				'default_value'     => 'Ihre Arbeitszeiten:',
				'maxlength'         => '',
				'placeholder'       => '',
				'prepend'           => '',
				'append'            => '',
				'key'               => 'field_57ff36a6dfd62',
				'label'             => 'Überschrift',
				'name'              => 'hours_headline',
				'type'              => 'text',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
			),
			array(
				'multiple'          => 0,
				'allow_null'        => 1,
				'choices'           => array(
					'Vollzeit' => 'Vollzeit',
					'Teilzeit' => 'Teilzeit',
				),
				'default_value'     => array(),
				'ui'                => 0,
				'ajax'              => 0,
				'placeholder'       => '',
				'return_format'     => 'value',
				'key'               => 'field_56deecfdac6ce',
				'label'             => 'Art',
				'name'              => 'hours_type',
				'type'              => 'select',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'disabled'          => 0,
				'readonly'          => 0,
			),
			array(
				'default_value'     => '',
				'maxlength'         => '',
				'placeholder'       => '',
				'prepend'           => '',
				'append'            => '',
				'key'               => 'field_56deed95ac6cf',
				'label'             => 'Stunden',
				'name'              => 'hours_amount',
				'type'              => 'text',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'readonly'          => 0,
				'disabled'          => 0,
			),
			array(
				'placement'         => 'top',
				'endpoint'          => 0,
				'key'               => 'field_56deec64ac6c9',
				'label'             => 'Gehalt',
				'name'              => '',
				'type'              => 'tab',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
			),
			array(
				'default_value'     => 'Ihr Einstiegsgehalt:',
				'maxlength'         => '',
				'placeholder'       => '',
				'prepend'           => '',
				'append'            => '',
				'key'               => 'field_57ff368fdfd61',
				'label'             => 'Überschrift',
				'name'              => 'salary_headline',
				'type'              => 'text',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
			),
			array(
				'default_value'     => '',
				'maxlength'         => '',
				'placeholder'       => '',
				'prepend'           => '',
				'append'            => '',
				'key'               => 'field_56deede1ac6d0',
				'label'             => 'Währung',
				'name'              => 'salary_currency',
				'type'              => 'text',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'readonly'          => 0,
				'disabled'          => 0,
			),
			array(
				'default_value'     => '',
				'maxlength'         => '',
				'placeholder'       => '',
				'prepend'           => '',
				'append'            => '',
				'key'               => 'field_56deee06ac6d1',
				'label'             => 'Gehalt',
				'name'              => 'salary_amount',
				'type'              => 'text',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'readonly'          => 0,
				'disabled'          => 0,
			),
			array(
				'placement'         => 'top',
				'endpoint'          => 0,
				'key'               => 'field_56deec79ac6ca',
				'label'             => 'Job-Beschreibung',
				'name'              => '',
				'type'              => 'tab',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
			),
			array(
				'default_value'     => 'Das erwartet Sie:',
				'maxlength'         => '',
				'placeholder'       => '',
				'prepend'           => '',
				'append'            => '',
				'key'               => 'field_57ff33f9877ed',
				'label'             => 'Überschrift',
				'name'              => 'description_headline',
				'type'              => 'text',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
			),
			array(
				'tabs'              => 'all',
				'toolbar'           => 'full',
				'media_upload'      => 1,
				'default_value'     => '',
				'delay'             => 0,
				'key'               => 'field_56deee1dac6d2',
				'label'             => 'Beschreibung',
				'name'              => 'description',
				'type'              => 'wysiwyg',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
			),
			array(
				'placement'         => 'top',
				'endpoint'          => 0,
				'key'               => 'field_56deec9eac6cb',
				'label'             => 'Voraussetzungen',
				'name'              => '',
				'type'              => 'tab',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
			),
			array(
				'default_value'     => 'Das sollten Sie mitbringen:',
				'maxlength'         => '',
				'placeholder'       => '',
				'prepend'           => '',
				'append'            => '',
				'key'               => 'field_57ff3343877ec',
				'label'             => 'Überschrift',
				'name'              => 'requirements_headline',
				'type'              => 'text',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
			),
			array(
				'sub_fields'        => array(
					array(
						'default_value'     => '',
						'new_lines'         => '',
						'maxlength'         => '',
						'placeholder'       => '',
						'rows'              => 3,
						'key'               => 'field_56def2b3ac6d4',
						'label'             => 'Text',
						'name'              => 'text',
						'type'              => 'textarea',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'readonly'          => 0,
						'disabled'          => 0,
					),
				),
				'min'               => 0,
				'max'               => 0,
				'layout'            => 'table',
				'button_label'      => 'Eintrag hinzufügen',
				'collapsed'         => '',
				'key'               => 'field_56def291ac6d3',
				'label'             => 'Voraussetzungen',
				'name'              => 'requirements',
				'type'              => 'repeater',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
			),
			array(
				'placement'         => 'top',
				'endpoint'          => 0,
				'key'               => 'field_56deecb4ac6cc',
				'label'             => 'Das bieten wir Ihnen',
				'name'              => '',
				'type'              => 'tab',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
			),
			array(
				'default_value'     => 'Das bieten wir Ihnen:',
				'maxlength'         => '',
				'placeholder'       => '',
				'prepend'           => '',
				'append'            => '',
				'key'               => 'field_57ff3449877ee',
				'label'             => 'Überschrift',
				'name'              => 'offers_headline',
				'type'              => 'text',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
			),
			array(
				'sub_fields'        => array(
					array(
						'default_value'     => '',
						'new_lines'         => '',
						'maxlength'         => '',
						'placeholder'       => '',
						'rows'              => 3,
						'key'               => 'field_56def2f8ac6d6',
						'label'             => 'Text',
						'name'              => 'text',
						'type'              => 'textarea',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'readonly'          => 0,
						'disabled'          => 0,
					),
				),
				'min'               => 0,
				'max'               => 0,
				'layout'            => 'table',
				'button_label'      => 'Eintrag hinzufügen',
				'collapsed'         => '',
				'key'               => 'field_56def2f8ac6d5',
				'label'             => 'Angebot',
				'name'              => 'offers',
				'type'              => 'repeater',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
			),
			array(
				'placement'         => 'top',
				'endpoint'          => 0,
				'key'               => 'field_57ebb58b0d04d',
				'label'             => 'Ansprechpartner',
				'name'              => '',
				'type'              => 'tab',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
			),
			array(
				'default_value'     => 'Ihr Ansprechpartner:',
				'maxlength'         => '',
				'placeholder'       => '',
				'prepend'           => '',
				'append'            => '',
				'key'               => 'field_57ff346a877ef',
				'label'             => 'Überschrift',
				'name'              => 'contact_headline',
				'type'              => 'text',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
			),
			array(
				'post_type'         => array(
					0 => 'mitarbeiter',
				),
				'taxonomy'          => array(),
				'allow_null'        => 1,
				'multiple'          => 0,
				'return_format'     => 'id',
				'ui'                => 1,
				'key'               => 'field_57ebb59a0d04e',
				'label'             => 'Ansprechpartner',
				'name'              => 'contact_person',
				'type'              => 'post_object',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
			),
			array(
				'placement'         => 'top',
				'endpoint'          => 0,
				'key'               => 'field_57ff350dc4b6a',
				'label'             => 'Texte Allgemein',
				'name'              => '',
				'type'              => 'tab',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
			),
			array(
				'default_value'     => 'Wir suchen derzeit eine/n:',
				'maxlength'         => '',
				'placeholder'       => '',
				'prepend'           => '',
				'append'            => '',
				'key'               => 'field_57ff3520c4b6b',
				'label'             => 'Überschrift',
				'name'              => 'headline',
				'type'              => 'text',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
			),
			array(
				'default_value'     => 'Bewerben Sie sich jetzt!',
				'maxlength'         => '',
				'placeholder'       => '',
				'prepend'           => '',
				'append'            => '',
				'key'               => 'field_57ff356ec4b6c',
				'label'             => 'Call-to-action-Button Beschriftung',
				'name'              => 'cta_label',
				'type'              => 'text',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
			),
		),
		'location'              => array(
			array(
				array(
					'param'    => 'post_type',
					'operator' => '==',
					'value'    => 'stellenangebot',
				),
			),
		),
		'menu_order'            => 0,
		'position'              => 'acf_after_title',
		'style'                 => 'default',
		'label_placement'       => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen'        => array(
			0 => 'the_content',
		),
		'active'                => 1,
		'description'           => '',
	) );

endif;

if ( function_exists( 'acf_add_local_field_group' ) ):

	acf_add_local_field_group( array(
		'key'                   => 'group_56def61c65650',
		'title'                 => 'Job-Kontaktinformationen',
		'fields'                => array(
			array(
				'tabs'              => 'all',
				'toolbar'           => 'full',
				'media_upload'      => 1,
				'default_value'     => '',
				'delay'             => 0,
				'key'               => 'field_56def639f2684',
				'label'             => 'Kontaktinformationen',
				'name'              => 'job_contact_info',
				'type'              => 'wysiwyg',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
			),
			array(
				'post_type'         => array(
					0 => 'mitarbeiter',
				),
				'taxonomy'          => array(),
				'allow_null'        => 1,
				'multiple'          => 0,
				'return_format'     => 'object',
				'ui'                => 1,
				'key'               => 'field_56def691f2685',
				'label'             => 'Kontaktperson',
				'name'              => 'job_contact_person',
				'type'              => 'post_object',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
			),
			array(
				'allow_null'        => 1,
				'multiple'          => 0,
				'disable'           => '',
				'key'               => 'field_56def6ccdd04e',
				'label'             => 'Kontaktformular',
				'name'              => 'job_contact_form',
				'type'              => 'cf7',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
			),
		),
		'location'              => array(
			array(
				array(
					'param'    => 'options_page',
					'operator' => '==',
					'value'    => 'theme-general-settings',
				),
			),
		),
		'menu_order'            => 0,
		'position'              => 'normal',
		'style'                 => 'default',
		'label_placement'       => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen'        => '',
		'active'                => 1,
		'description'           => '',
	) );

endif;