<?php

if ( function_exists( 'acf_add_local_field_group' ) ):

	acf_add_local_field_group( array(
		'key'                   => 'group_5512b5a5a55f3',
		'title'                 => 'Flexible Content',
		'fields'                => array(
			array(
				'key'               => 'field_5422a3a4a988b',
				'label'             => 'Zeilen',
				'name'              => 'flexible-content-rows',
				'type'              => 'flexible_content',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'button_label'      => '',
				'min'               => '',
				'max'               => '',
				'layouts'           => array(
					array(
						'key'        => '56a87e95b0837',
						'name'       => 'flexible-content-layout--headline',
						'label'      => 'Überschrift',
						'display'    => 'block',
						'sub_fields' => array(
							array(
								'key'               => 'field_56a883bc53b7b',
								'label'             => 'Überschrift',
								'name'              => 'headline',
								'type'              => 'text',
								'instructions'      => '',
								'required'          => 0,
								'conditional_logic' => 0,
								'wrapper'           => array(
									'width' => '',
									'class' => '',
									'id'    => '',
								),
								'default_value'     => '',
								'maxlength'         => '',
								'placeholder'       => '',
								'prepend'           => '',
								'append'            => '',
								'readonly'          => 0,
								'disabled'          => 0,
							),
							array(
								'key'               => 'field_575188762c57b',
								'label'             => 'Überschrift-Art',
								'name'              => 'headline_type',
								'type'              => 'select',
								'instructions'      => '',
								'required'          => 0,
								'conditional_logic' => 0,
								'wrapper'           => array(
									'width' => '',
									'class' => '',
									'id'    => '',
								),
								'multiple'          => 0,
								'allow_null'        => 0,
								'choices'           => array(
									'h1' => 'h1',
									'h2' => 'h2',
									'h3' => 'h3',
									'h4' => 'h4',
									'h5' => 'h5',
									'h6' => 'h6',
								),
								'default_value'     => array(
									0 => 'h2',
								),
								'ui'                => 0,
								'ajax'              => 0,
								'placeholder'       => '',
								'return_format'     => 'value',
								'disabled'          => 0,
								'readonly'          => 0,
							),
						),
						'min'        => '',
						'max'        => '',
					),
					array(
						'key'        => '5813447a89f3c',
						'name'       => 'flexible-content-layout--text',
						'label'      => 'WYSIWYG-Editor',
						'display'    => 'block',
						'sub_fields' => array(
							array(
								'key'               => 'field_5813447a89f3d',
								'label'             => 'Überschrift',
								'name'              => 'headline',
								'type'              => 'clone',
								'instructions'      => '',
								'required'          => 0,
								'conditional_logic' => 0,
								'wrapper'           => array(
									'width' => '',
									'class' => '',
									'id'    => '',
								),
								'clone'             => array(
									0 => 'field_56a883bc53b7b',
									1 => 'field_575188762c57b',
								),
								'prefix_label'      => 0,
								'prefix_name'       => 0,
								'display'           => 'seamless',
								'layout'            => 'block',
							),
							array(
								'key'               => 'field_5813447a89f3f',
								'label'             => 'Text',
								'name'              => 'text',
								'type'              => 'wysiwyg',
								'instructions'      => '',
								'required'          => 0,
								'conditional_logic' => 0,
								'wrapper'           => array(
									'width' => '',
									'class' => '',
									'id'    => '',
								),
								'tabs'              => 'all',
								'toolbar'           => 'full',
								'media_upload'      => 1,
								'default_value'     => '',
								'delay'             => 0,
							),
							array(
								'key'               => 'field_5813447a89f40',
								'label'             => 'Link',
								'name'              => 'link',
								'type'              => 'post_object',
								'instructions'      => '',
								'required'          => 0,
								'conditional_logic' => 0,
								'wrapper'           => array(
									'width' => '',
									'class' => '',
									'id'    => '',
								),
								'post_type'         => array(),
								'taxonomy'          => array(),
								'allow_null'        => 0,
								'multiple'          => 0,
								'return_format'     => 'object',
								'ui'                => 1,
							),
						),
						'min'        => '',
						'max'        => '',
					),
					array(
						'key'        => '58b54e8863129',
						'name'       => 'flexible-content-layout--text-with-image',
						'label'      => 'Text mit Bild (Spalten)',
						'display'    => 'block',
						'sub_fields' => array(
							array(
								'key'               => 'field_58b54e886312a',
								'label'             => 'Überschrift',
								'name'              => 'headline',
								'type'              => 'clone',
								'instructions'      => '',
								'required'          => 0,
								'conditional_logic' => 0,
								'wrapper'           => array(
									'width' => '',
									'class' => '',
									'id'    => '',
								),
								'clone'             => array(
									0 => 'field_56a883bc53b7b',
									1 => 'field_575188762c57b',
								),
								'prefix_label'      => 0,
								'prefix_name'       => 0,
								'display'           => 'seamless',
								'layout'            => 'block',
							),
							array(
								'key'               => 'field_58b54eba63130',
								'label'             => 'Spalten',
								'name'              => 'columns',
								'type'              => 'repeater',
								'instructions'      => '',
								'required'          => 0,
								'conditional_logic' => 0,
								'wrapper'           => array(
									'width' => '',
									'class' => '',
									'id'    => '',
								),
								'collapsed'         => '',
								'min'               => 1,
								'max'               => 4,
								'layout'            => 'block',
								'button_label'      => 'Spalte hinzufügen',
								'sub_fields'        => array(
									array(
										'key'               => 'field_58b67c780db98',
										'label'             => 'Spalte',
										'name'              => 'column',
										'type'              => 'clone',
										'instructions'      => '',
										'required'          => 0,
										'conditional_logic' => 0,
										'wrapper'           => array(
											'width' => '',
											'class' => '',
											'id'    => '',
										),
										'clone'             => array(
											0 => 'group_58b67a72e42d7',
										),
										'prefix_label'      => 0,
										'prefix_name'       => 0,
										'display'           => 'seamless',
										'layout'            => 'block',
									),
								),
							),
						),
						'min'        => '',
						'max'        => '',
					),
					array(
						'key'        => '5875e6113ab4f',
						'name'       => 'flexible-content-layout--definitions',
						'label'      => 'Definitionen',
						'display'    => 'block',
						'sub_fields' => array(
							array(
								'key'               => 'field_5875e6113ab50',
								'label'             => 'Überschrift',
								'name'              => 'headline',
								'type'              => 'clone',
								'instructions'      => '',
								'required'          => 0,
								'conditional_logic' => 0,
								'wrapper'           => array(
									'width' => '',
									'class' => '',
									'id'    => '',
								),
								'clone'             => array(
									0 => 'field_56a883bc53b7b',
									1 => 'field_575188762c57b',
								),
								'prefix_label'      => 0,
								'prefix_name'       => 0,
								'display'           => 'seamless',
								'layout'            => 'block',
							),
							array(
								'key'               => 'field_5875e62a3ab53',
								'label'             => 'Definitionen',
								'name'              => 'definitions',
								'type'              => 'repeater',
								'instructions'      => '',
								'required'          => 0,
								'conditional_logic' => 0,
								'wrapper'           => array(
									'width' => '',
									'class' => '',
									'id'    => '',
								),
								'min'               => 1,
								'max'               => 1,
								'layout'            => 'block',
								'button_label'      => '',
								'collapsed'         => '',
								'sub_fields'        => array(
									array(
										'key'               => 'field_5875e6513ab54',
										'label'             => 'Titel',
										'name'              => 'title',
										'type'              => 'text',
										'instructions'      => '',
										'required'          => 0,
										'conditional_logic' => 0,
										'wrapper'           => array(
											'width' => '',
											'class' => '',
											'id'    => '',
										),
										'default_value'     => '',
										'maxlength'         => '',
										'placeholder'       => '',
										'prepend'           => '',
										'append'            => '',
									),
									array(
										'key'               => 'field_5875e6603ab55',
										'label'             => 'Defintion',
										'name'              => 'data',
										'type'              => 'textarea',
										'instructions'      => '',
										'required'          => 0,
										'conditional_logic' => 0,
										'wrapper'           => array(
											'width' => '',
											'class' => '',
											'id'    => '',
										),
										'default_value'     => '',
										'new_lines'         => 'wpautop',
										'maxlength'         => '',
										'placeholder'       => '',
										'rows'              => '',
									),
								),
							),
						),
						'min'        => '',
						'max'        => '',
					),
					array(
						'key'        => '5878a912fdfce',
						'name'       => 'flexible-content-layout--accordion',
						'label'      => 'Accordion',
						'display'    => 'block',
						'sub_fields' => array(
							array(
								'key'               => 'field_5875f4a1f57d6',
								'label'             => 'Überschrift',
								'name'              => 'headline',
								'type'              => 'clone',
								'instructions'      => '',
								'required'          => 0,
								'conditional_logic' => 0,
								'wrapper'           => array(
									'width' => '',
									'class' => '',
									'id'    => '',
								),
								'clone'             => array(
									0 => 'field_56a883bc53b7b',
									1 => 'field_575188762c57b',
								),
								'prefix_label'      => 0,
								'prefix_name'       => 0,
								'display'           => 'seamless',
								'layout'            => 'block',
							),
							array(
								'key'               => 'field_5875f4a1f57d7',
								'label'             => 'Abschnitte',
								'name'              => 'sections',
								'type'              => 'repeater',
								'instructions'      => '',
								'required'          => 0,
								'conditional_logic' => 0,
								'wrapper'           => array(
									'width' => '',
									'class' => '',
									'id'    => '',
								),
								'collapsed'         => '',
								'min'               => 1,
								'max'               => 0,
								'layout'            => 'block',
								'button_label'      => 'Abschnitt hinzufügen',
								'sub_fields'        => array(
									array(
										'key'               => 'field_58f9f2d3996b4',
										'label'             => 'section',
										'name'              => 'section',
										'type'              => 'clone',
										'instructions'      => '',
										'required'          => 0,
										'conditional_logic' => 0,
										'wrapper'           => array(
											'width' => '',
											'class' => '',
											'id'    => '',
										),
										'clone'             => array(
											0 => 'field_58b67a8488f12',
											1 => 'field_58b67acf88f13',
											2 => 'field_58f854072329a',
											3 => 'field_58b67af588f15',
											4 => 'field_58f8549d2329b',
											5 => 'field_58f857d533a0f',
											6 => 'field_58f8576833a0e',
										),
										'display'           => 'seamless',
										'layout'            => 'block',
										'prefix_label'      => 0,
										'prefix_name'       => 0,
									),
								),
							),
						),
						'min'        => '',
						'max'        => '',
					),
					array(
						'key'        => '57bac6fc44f38',
						'name'       => 'flexible-content-layout--gallery',
						'label'      => 'Galerie',
						'display'    => 'block',
						'sub_fields' => array(
							array(
								'key'               => 'field_57c679dc04965',
								'label'             => 'Überschrift',
								'name'              => 'headline',
								'type'              => 'clone',
								'instructions'      => '',
								'required'          => 0,
								'conditional_logic' => 0,
								'wrapper'           => array(
									'width' => '',
									'class' => '',
									'id'    => '',
								),
								'clone'             => array(
									0 => 'field_56a883bc53b7b',
									1 => 'field_575188762c57b',
								),
								'prefix_label'      => 0,
								'prefix_name'       => 0,
								'display'           => 'seamless',
								'layout'            => 'block',
							),
							array(
								'key'               => 'field_57bac6fc44f39',
								'label'             => 'Galerie',
								'name'              => 'gallery',
								'type'              => 'gallery',
								'instructions'      => '',
								'required'          => 1,
								'conditional_logic' => 0,
								'wrapper'           => array(
									'width' => '',
									'class' => '',
									'id'    => '',
								),
								'library'           => 'all',
								'min'               => '',
								'max'               => '',
								'min_width'         => '',
								'min_height'        => '',
								'min_size'          => '',
								'max_width'         => '',
								'max_height'        => '',
								'max_size'          => '',
								'mime_types'        => '',
								'insert'            => 'append',
							),
						),
						'min'        => '',
						'max'        => '',
					),
					array(
						'key'        => '57c55b807a5f8',
						'name'       => 'flexible-content-layout--list',
						'label'      => 'Liste',
						'display'    => 'block',
						'sub_fields' => array(
							array(
								'key'               => 'field_57c55bbc7a5fb',
								'label'             => 'Überschrift',
								'name'              => 'headline',
								'type'              => 'clone',
								'instructions'      => '',
								'required'          => 0,
								'conditional_logic' => 0,
								'wrapper'           => array(
									'width' => '',
									'class' => '',
									'id'    => '',
								),
								'clone'             => array(
									0 => 'field_56a883bc53b7b',
									1 => 'field_575188762c57b',
								),
								'prefix_label'      => 0,
								'prefix_name'       => 0,
								'display'           => 'seamless',
								'layout'            => 'block',
							),
							array(
								'key'               => 'field_57c55bfd7a5fd',
								'label'             => 'Liste',
								'name'              => 'items',
								'type'              => 'repeater',
								'instructions'      => '',
								'required'          => 0,
								'conditional_logic' => 0,
								'wrapper'           => array(
									'width' => '',
									'class' => '',
									'id'    => '',
								),
								'min'               => 1,
								'max'               => 0,
								'layout'            => 'table',
								'button_label'      => 'Listenelement hinzufügen',
								'collapsed'         => '',
								'sub_fields'        => array(
									array(
										'key'               => 'field_57c55c687a5ff',
										'label'             => 'Titel',
										'name'              => 'title',
										'type'              => 'text',
										'instructions'      => '',
										'required'          => 1,
										'conditional_logic' => 0,
										'wrapper'           => array(
											'width' => '',
											'class' => '',
											'id'    => '',
										),
										'default_value'     => '',
										'maxlength'         => '',
										'placeholder'       => '',
										'prepend'           => '',
										'append'            => '',
										'readonly'          => 0,
										'disabled'          => 0,
									),
									array(
										'key'               => 'field_57c55c927a600',
										'label'             => 'Liste',
										'name'              => 'items',
										'type'              => 'repeater',
										'instructions'      => '',
										'required'          => 0,
										'conditional_logic' => 0,
										'wrapper'           => array(
											'width' => '',
											'class' => '',
											'id'    => '',
										),
										'min'               => 0,
										'max'               => 0,
										'layout'            => 'block',
										'button_label'      => 'Listenelement hinzufügen',
										'collapsed'         => '',
										'sub_fields'        => array(
											array(
												'key'               => 'field_57c55ccf7a601',
												'label'             => 'Titel',
												'name'              => 'title',
												'type'              => 'text',
												'instructions'      => '',
												'required'          => 1,
												'conditional_logic' => 0,
												'wrapper'           => array(
													'width' => '',
													'class' => '',
													'id'    => '',
												),
												'default_value'     => '',
												'maxlength'         => '',
												'placeholder'       => '',
												'prepend'           => '',
												'append'            => '',
												'readonly'          => 0,
												'disabled'          => 0,
											),
										),
									),
								),
							),
						),
						'min'        => '',
						'max'        => '',
					),
					array(
						'key'        => '57c55ba07a5fa',
						'name'       => 'flexible-content-layout--table',
						'label'      => 'Tabelle',
						'display'    => 'block',
						'sub_fields' => array(
							array(
								'key'               => 'field_57c55be07a5fc',
								'label'             => 'Überschrift',
								'name'              => 'headline',
								'type'              => 'clone',
								'instructions'      => '',
								'required'          => 0,
								'conditional_logic' => 0,
								'wrapper'           => array(
									'width' => '',
									'class' => '',
									'id'    => '',
								),
								'clone'             => array(
									0 => 'field_56a883bc53b7b',
									1 => 'field_575188762c57b',
								),
								'prefix_label'      => 0,
								'prefix_name'       => 0,
								'display'           => 'seamless',
								'layout'            => 'block',
							),
							array(
								'key'               => 'field_57c55d2e5454f',
								'label'             => 'Zeilen',
								'name'              => 'rows',
								'type'              => 'repeater',
								'instructions'      => '',
								'required'          => 1,
								'conditional_logic' => 0,
								'wrapper'           => array(
									'width' => '',
									'class' => '',
									'id'    => '',
								),
								'collapsed'         => '',
								'min'               => 1,
								'max'               => 0,
								'layout'            => 'row',
								'button_label'      => 'Zeile hinzufügen',
								'sub_fields'        => array(
									array(
										'key'               => 'field_57c55d6854550',
										'label'             => 'Spalten',
										'name'              => 'columns',
										'type'              => 'repeater',
										'instructions'      => '',
										'required'          => 1,
										'conditional_logic' => 0,
										'wrapper'           => array(
											'width' => '',
											'class' => '',
											'id'    => '',
										),
										'collapsed'         => '',
										'min'               => 1,
										'max'               => 4,
										'layout'            => 'table',
										'button_label'      => 'Spalte hinzufügen',
										'sub_fields'        => array(
											array(
												'key'               => 'field_57c55de254551',
												'label'             => 'Text',
												'name'              => 'text',
												'type'              => 'textarea',
												'instructions'      => '',
												'required'          => 0,
												'conditional_logic' => 0,
												'wrapper'           => array(
													'width' => '',
													'class' => '',
													'id'    => '',
												),
												'default_value'     => '',
												'new_lines'         => '',
												'maxlength'         => '',
												'placeholder'       => '',
												'rows'              => 2,
												'readonly'          => 0,
												'disabled'          => 0,
											),
										),
									),
								),
							),
						),
						'min'        => '',
						'max'        => '',
					),
					array(
						'key'        => '581b4e3eb9c66',
						'name'       => 'flexible-content-layout--downloads',
						'label'      => 'Downloads',
						'display'    => 'block',
						'sub_fields' => array(
							array(
								'key'               => 'field_581b4e3eb9c67',
								'label'             => 'Überschrift',
								'name'              => 'headline',
								'type'              => 'clone',
								'instructions'      => '',
								'required'          => 0,
								'conditional_logic' => 0,
								'wrapper'           => array(
									'width' => '',
									'class' => '',
									'id'    => '',
								),
								'clone'             => array(
									0 => 'field_56a883bc53b7b',
									1 => 'field_575188762c57b',
								),
								'prefix_label'      => 0,
								'prefix_name'       => 0,
								'display'           => 'seamless',
								'layout'            => 'block',
							),
							array(
								'key'               => 'field_581b4e3eb9c69',
								'label'             => 'Download-Kategorie',
								'name'              => 'download_categories',
								'type'              => 'repeater',
								'instructions'      => '',
								'required'          => 1,
								'conditional_logic' => 0,
								'wrapper'           => array(
									'width' => '',
									'class' => '',
									'id'    => '',
								),
								'min'               => 1,
								'max'               => 0,
								'layout'            => 'block',
								'button_label'      => 'Download-Kategorie hinzufügen',
								'collapsed'         => '',
								'sub_fields'        => array(
									array(
										'key'               => 'field_581b4fbab9c6d',
										'label'             => 'Titel',
										'name'              => 'title',
										'type'              => 'text',
										'instructions'      => '',
										'required'          => 0,
										'conditional_logic' => 0,
										'wrapper'           => array(
											'width' => '',
											'class' => '',
											'id'    => '',
										),
										'default_value'     => '',
										'maxlength'         => '',
										'placeholder'       => '',
										'prepend'           => '',
										'append'            => '',
										'readonly'          => 0,
										'disabled'          => 0,
									),
									array(
										'key'               => 'field_581b4fc8b9c6e',
										'label'             => 'Downloads',
										'name'              => 'downloads',
										'type'              => 'repeater',
										'instructions'      => '',
										'required'          => 0,
										'conditional_logic' => 0,
										'wrapper'           => array(
											'width' => '',
											'class' => '',
											'id'    => '',
										),
										'min'               => 1,
										'max'               => 0,
										'layout'            => 'table',
										'button_label'      => 'Download hinzufügen',
										'collapsed'         => '',
										'sub_fields'        => array(
											array(
												'key'               => 'field_581b4fdfb9c6f',
												'label'             => 'Titel',
												'name'              => 'title',
												'type'              => 'text',
												'instructions'      => '',
												'required'          => 0,
												'conditional_logic' => 0,
												'wrapper'           => array(
													'width' => '',
													'class' => '',
													'id'    => '',
												),
												'default_value'     => '',
												'maxlength'         => '',
												'placeholder'       => '',
												'prepend'           => '',
												'append'            => '',
												'readonly'          => 0,
												'disabled'          => 0,
											),
											array(
												'key'               => 'field_581b4ff8b9c70',
												'label'             => 'Datei',
												'name'              => 'file',
												'type'              => 'file',
												'instructions'      => '',
												'required'          => 0,
												'conditional_logic' => 0,
												'wrapper'           => array(
													'width' => '',
													'class' => '',
													'id'    => '',
												),
												'return_format'     => 'array',
												'library'           => 'all',
												'min_size'          => '',
												'max_size'          => '',
												'mime_types'        => '',
											),
											array(
												'key'               => 'field_581b5019b9c71',
												'label'             => 'In neuem Fenster öffnen',
												'name'              => 'target',
												'type'              => 'true_false',
												'instructions'      => '',
												'required'          => 0,
												'conditional_logic' => 0,
												'wrapper'           => array(
													'width' => '',
													'class' => '',
													'id'    => '',
												),
												'default_value'     => 1,
												'message'           => '',
												'ui'                => 0,
												'ui_on_text'        => '',
												'ui_off_text'       => '',
											),
										),
									),
								),
							),
						),
						'min'        => '',
						'max'        => '',
					),
					array(
						'key'        => '5876161dd152d',
						'name'       => 'flexible-content-layout--map',
						'label'      => 'Google Map',
						'display'    => 'block',
						'sub_fields' => array(
							array(
								'key'               => 'field_5876161dd152e',
								'label'             => 'Überschrift',
								'name'              => 'headline',
								'type'              => 'clone',
								'instructions'      => '',
								'required'          => 0,
								'conditional_logic' => 0,
								'wrapper'           => array(
									'width' => '',
									'class' => '',
									'id'    => '',
								),
								'clone'             => array(
									0 => 'field_56a883bc53b7b',
									1 => 'field_575188762c57b',
								),
								'prefix_label'      => 0,
								'prefix_name'       => 0,
								'display'           => 'seamless',
								'layout'            => 'block',
							),
							array(
								'key'               => 'field_5877a9f651877',
								'label'             => 'Globalen Standort verwenden',
								'name'              => 'use_global_location',
								'type'              => 'true_false',
								'instructions'      => '',
								'required'          => 0,
								'conditional_logic' => 0,
								'wrapper'           => array(
									'width' => '',
									'class' => '',
									'id'    => '',
								),
								'default_value'     => 1,
								'message'           => '',
								'ui'                => 1,
								'ui_on_text'        => '',
								'ui_off_text'       => '',
							),
							array(
								'key'               => 'field_587616cbd1539',
								'label'             => 'Name des Standorts',
								'name'              => 'title',
								'type'              => 'text',
								'instructions'      => '',
								'required'          => 0,
								'conditional_logic' => array(
									array(
										array(
											'field'    => 'field_5877a9f651877',
											'operator' => '!=',
											'value'    => '1',
										),
									),
								),
								'wrapper'           => array(
									'width' => '',
									'class' => '',
									'id'    => '',
								),
								'default_value'     => '',
								'maxlength'         => '',
								'placeholder'       => '',
								'prepend'           => '',
								'append'            => '',
							),
							array(
								'key'               => 'field_5876165ad1536',
								'label'             => 'Straße, Nr.',
								'name'              => 'address',
								'type'              => 'text',
								'instructions'      => '',
								'required'          => 0,
								'conditional_logic' => array(
									array(
										array(
											'field'    => 'field_5877a9f651877',
											'operator' => '!=',
											'value'    => '1',
										),
									),
								),
								'wrapper'           => array(
									'width' => '',
									'class' => '',
									'id'    => '',
								),
								'default_value'     => '',
								'maxlength'         => '',
								'placeholder'       => '',
								'prepend'           => '',
								'append'            => '',
							),
							array(
								'key'               => 'field_5876166bd1537',
								'label'             => 'PLZ',
								'name'              => 'postal_code',
								'type'              => 'text',
								'instructions'      => '',
								'required'          => 0,
								'conditional_logic' => array(
									array(
										array(
											'field'    => 'field_5877a9f651877',
											'operator' => '!=',
											'value'    => '1',
										),
									),
								),
								'wrapper'           => array(
									'width' => '',
									'class' => '',
									'id'    => '',
								),
								'default_value'     => '',
								'maxlength'         => '',
								'placeholder'       => '',
								'prepend'           => '',
								'append'            => '',
							),
							array(
								'key'               => 'field_587616c0d1538',
								'label'             => 'Ort',
								'name'              => 'city',
								'type'              => 'text',
								'instructions'      => '',
								'required'          => 0,
								'conditional_logic' => array(
									array(
										array(
											'field'    => 'field_5877a9f651877',
											'operator' => '!=',
											'value'    => '1',
										),
									),
								),
								'wrapper'           => array(
									'width' => '',
									'class' => '',
									'id'    => '',
								),
								'default_value'     => '',
								'maxlength'         => '',
								'placeholder'       => '',
								'prepend'           => '',
								'append'            => '',
							),
						),
						'min'        => '',
						'max'        => '',
					),
					array(
						'key'        => '5878bbb439099',
						'name'       => 'flexible-content-layout--contact-form',
						'label'      => 'Kontaktformular',
						'display'    => 'block',
						'sub_fields' => array(
							array(
								'key'               => 'field_5878bbb43909a',
								'label'             => 'Überschrift',
								'name'              => 'headline',
								'type'              => 'clone',
								'instructions'      => '',
								'required'          => 0,
								'conditional_logic' => 0,
								'wrapper'           => array(
									'width' => '',
									'class' => '',
									'id'    => '',
								),
								'clone'             => array(
									0 => 'field_56a883bc53b7b',
									1 => 'field_575188762c57b',
								),
								'prefix_label'      => 0,
								'prefix_name'       => 0,
								'display'           => 'seamless',
								'layout'            => 'block',
							),
							array(
								'key'               => 'field_5878bbcf390a0',
								'label'             => 'Formular',
								'name'              => 'form',
								'type'              => 'cf7',
								'instructions'      => '',
								'required'          => 0,
								'conditional_logic' => 0,
								'wrapper'           => array(
									'width' => '',
									'class' => '',
									'id'    => '',
								),
								'allow_null'        => 1,
								'multiple'          => 0,
								'disable'           => '',
							),
						),
						'min'        => '',
						'max'        => '',
					),
					array(
						'key'        => '58b7e6137e33d',
						'name'       => 'flexible-content-layout--tabs',
						'label'      => 'Tabs',
						'display'    => 'block',
						'sub_fields' => array(
							array(
								'key'               => 'field_58b7e6137e33e',
								'label'             => 'Überschrift',
								'name'              => 'headline',
								'type'              => 'clone',
								'instructions'      => '',
								'required'          => 0,
								'conditional_logic' => 0,
								'wrapper'           => array(
									'width' => '',
									'class' => '',
									'id'    => '',
								),
								'clone'             => array(
									0 => 'field_56a883bc53b7b',
									1 => 'field_575188762c57b',
								),
								'prefix_label'      => 0,
								'prefix_name'       => 0,
								'display'           => 'seamless',
								'layout'            => 'block',
							),
							array(
								'key'               => 'field_58b7e6c47e340',
								'label'             => 'Tab-Platzierung',
								'name'              => 'tab_placement',
								'type'              => 'select',
								'instructions'      => '',
								'required'          => 1,
								'conditional_logic' => 0,
								'wrapper'           => array(
									'width' => '',
									'class' => '',
									'id'    => '',
								),
								'multiple'          => 0,
								'allow_null'        => 0,
								'choices'           => array(
									'left'  => 'Links',
									'right' => 'Rechts',
									'top'   => 'Oben',
								),
								'default_value'     => array(),
								'ui'                => 1,
								'ajax'              => 0,
								'placeholder'       => '',
								'return_format'     => 'value',
							),
							array(
								'key'               => 'field_58b7e8b1e6228',
								'label'             => 'Tabs',
								'name'              => 'tabs',
								'type'              => 'repeater',
								'instructions'      => '',
								'required'          => 0,
								'conditional_logic' => 0,
								'wrapper'           => array(
									'width' => '',
									'class' => '',
									'id'    => '',
								),
								'collapsed'         => '',
								'min'               => 1,
								'max'               => 4,
								'layout'            => 'table',
								'button_label'      => 'Tab hinzufügen',
								'sub_fields'        => array(
									array(
										'key'               => 'field_58b7e8bbe6229',
										'label'             => 'Tab',
										'name'              => 'tab',
										'type'              => 'clone',
										'instructions'      => '',
										'required'          => 0,
										'conditional_logic' => 0,
										'wrapper'           => array(
											'width' => '',
											'class' => '',
											'id'    => '',
										),
										'clone'             => array(
											0 => 'field_58b67a8488f12',
											1 => 'field_58b67ae888f14',
											2 => 'field_58b67af588f15',
											3 => 'field_58f7664fb7927',
											4 => 'field_58b67d590b8df',
											5 => 'field_58becbc769419',
											6 => 'field_58f76505d15d5',
										),
										'display'           => 'seamless',
										'layout'            => 'block',
										'prefix_label'      => 0,
										'prefix_name'       => 0,
									),
								),
							),
						),
						'min'        => '',
						'max'        => '',
					),
					array(
						'key'        => '58b833268909d',
						'name'       => 'flexible-content-layout--variable',
						'label'      => 'Variable Elemente (Spalten)',
						'display'    => 'block',
						'sub_fields' => array(
							array(
								'key'               => 'field_58b833268909e',
								'label'             => 'Überschrift',
								'name'              => 'headline',
								'type'              => 'clone',
								'instructions'      => '',
								'required'          => 0,
								'conditional_logic' => 0,
								'wrapper'           => array(
									'width' => '',
									'class' => '',
									'id'    => '',
								),
								'clone'             => array(
									0 => 'field_56a883bc53b7b',
									1 => 'field_575188762c57b',
								),
								'prefix_label'      => 0,
								'prefix_name'       => 0,
								'display'           => 'seamless',
								'layout'            => 'block',
							),
							array(
								'key'               => 'field_58b8336b890a3',
								'label'             => 'Spalten',
								'name'              => 'columns',
								'type'              => 'flexible_content',
								'instructions'      => '',
								'required'          => 0,
								'conditional_logic' => 0,
								'wrapper'           => array(
									'width' => '',
									'class' => '',
									'id'    => '',
								),
								'button_label'      => 'Spalte hinzufügen',
								'min'               => '',
								'max'               => 2,
								'layouts'           => array(
									array(
										'key'        => '58b8337fbb55d',
										'name'       => 'flexible-content-layout--linked-object',
										'label'      => 'Verlinktes Objekt',
										'display'    => 'block',
										'sub_fields' => array(
											array(
												'key'               => 'field_58b8344b890a4',
												'label'             => 'Verlinktes Objekt',
												'name'              => 'linked_object',
												'type'              => 'clone',
												'instructions'      => '',
												'required'          => 0,
												'conditional_logic' => 0,
												'wrapper'           => array(
													'width' => '',
													'class' => '',
													'id'    => '',
												),
												'clone'             => array(
													0 => 'group_58b67a72e42d7',
												),
												'prefix_label'      => 0,
												'prefix_name'       => 0,
												'display'           => 'seamless',
												'layout'            => '',
											),
										),
										'min'        => '',
										'max'        => '',
									),
									array(
										'key'        => '58b83ac3f42b2',
										'name'       => 'flexible-content-layout--tabs',
										'label'      => 'Tabs',
										'display'    => 'block',
										'sub_fields' => array(
											array(
												'key'               => 'field_58b83ac3f42b4',
												'label'             => 'Tabs',
												'name'              => 'tabs',
												'type'              => 'clone',
												'instructions'      => '',
												'required'          => 0,
												'conditional_logic' => 0,
												'wrapper'           => array(
													'width' => '',
													'class' => '',
													'id'    => '',
												),
												'clone'             => array(
													0 => 'field_58b7e6c47e340',
													1 => 'field_58b7e8b1e6228',
												),
												'prefix_label'      => 0,
												'prefix_name'       => 0,
												'display'           => 'seamless',
												'layout'            => 'block',
											),
										),
										'min'        => '',
										'max'        => '',
									),
								),
							),
						),
						'min'        => '',
						'max'        => '',
					),
					array(
						'key'        => '58da2510bb0f4',
						'name'       => 'flexible-content-layout--posts-referenzen',
						'label'      => 'Referenzen',
						'display'    => 'block',
						'sub_fields' => array(
							array(
								'key'               => 'field_58da2511bb0f5',
								'label'             => 'Überschrift',
								'name'              => 'headline',
								'type'              => 'clone',
								'instructions'      => '',
								'required'          => 0,
								'conditional_logic' => 0,
								'wrapper'           => array(
									'width' => '',
									'class' => '',
									'id'    => '',
								),
								'clone'             => array(
									0 => 'field_56a883bc53b7b',
									1 => 'field_575188762c57b',
								),
								'display'           => 'seamless',
								'layout'            => '',
								'prefix_label'      => 0,
								'prefix_name'       => 0,
							),
							array(
								'key'               => 'field_58db79c58b806',
								'label'             => 'Text',
								'name'              => 'text',
								'type'              => 'wysiwyg',
								'instructions'      => '',
								'required'          => 0,
								'conditional_logic' => 0,
								'wrapper'           => array(
									'width' => '',
									'class' => '',
									'id'    => '',
								),
								'default_value'     => '',
								'tabs'              => 'all',
								'toolbar'           => 'full',
								'media_upload'      => 1,
								'delay'             => 0,
							),
							array(
								'key'               => 'field_58da254fbb0fe',
								'label'             => 'Referenzen',
								'name'              => 'posts',
								'type'              => 'relationship',
								'instructions'      => '',
								'required'          => 0,
								'conditional_logic' => 0,
								'wrapper'           => array(
									'width' => '',
									'class' => '',
									'id'    => '',
								),
								'post_type'         => array(
									0 => 'referenz',
								),
								'taxonomy'          => array(),
								'filters'           => array(
									0 => 'search',
								),
								'elements'          => '',
								'min'               => '',
								'max'               => '',
								'return_format'     => 'id',
							),
							array(
								'key'               => 'field_58f75be6775e9',
								'label'             => 'Layout',
								'name'              => 'layout',
								'type'              => 'select',
								'instructions'      => '',
								'required'          => 0,
								'conditional_logic' => 0,
								'wrapper'           => array(
									'width' => '',
									'class' => '',
									'id'    => '',
								),
								'choices'           => array(
									'quote' => 'Zitate',
									'link'  => 'Links',
								),
								'default_value'     => array(
									0 => 'link',
								),
								'allow_null'        => 0,
								'multiple'          => 0,
								'ui'                => 1,
								'ajax'              => 0,
								'return_format'     => 'value',
								'placeholder'       => '',
							),
						),
						'min'        => '',
						'max'        => '',
					),
					array(
						'key'        => '58da253ebb0f9',
						'name'       => 'flexible-content-layout--posts-partnerschaften',
						'label'      => 'Partnerschaften',
						'display'    => 'block',
						'sub_fields' => array(
							array(
								'key'               => 'field_58da253ebb0fa',
								'label'             => 'Überschrift',
								'name'              => 'headline',
								'type'              => 'clone',
								'instructions'      => '',
								'required'          => 0,
								'conditional_logic' => 0,
								'wrapper'           => array(
									'width' => '',
									'class' => '',
									'id'    => '',
								),
								'clone'             => array(
									0 => 'field_56a883bc53b7b',
									1 => 'field_575188762c57b',
								),
								'display'           => 'seamless',
								'layout'            => 'block',
								'prefix_label'      => 0,
								'prefix_name'       => 0,
							),
							array(
								'key'               => 'field_58db79d38b807',
								'label'             => 'Text',
								'name'              => 'text',
								'type'              => 'wysiwyg',
								'instructions'      => '',
								'required'          => 0,
								'conditional_logic' => 0,
								'wrapper'           => array(
									'width' => '',
									'class' => '',
									'id'    => '',
								),
								'default_value'     => '',
								'tabs'              => 'all',
								'toolbar'           => 'full',
								'media_upload'      => 1,
								'delay'             => 0,
							),
							array(
								'key'               => 'field_58da259ebb0ff',
								'label'             => 'Partnerschaften',
								'name'              => 'posts',
								'type'              => 'relationship',
								'instructions'      => '',
								'required'          => 0,
								'conditional_logic' => 0,
								'wrapper'           => array(
									'width' => '',
									'class' => '',
									'id'    => '',
								),
								'post_type'         => array(
									0 => 'partnerschaft',
								),
								'taxonomy'          => array(),
								'filters'           => array(
									0 => 'search',
								),
								'elements'          => '',
								'min'               => '',
								'max'               => '',
								'return_format'     => 'id',
							),
						),
						'min'        => '',
						'max'        => '',
					),
				),
			),
		),
		'location'              => array(
			array(
				array(
					'param'    => 'post_type',
					'operator' => '==',
					'value'    => 'post',
				),
			),
			array(
				array(
					'param'    => 'post_type',
					'operator' => '==',
					'value'    => 'page',
				),
				array(
					'param'    => 'page_type',
					'operator' => '!=',
					'value'    => 'posts_page',
				),
				array(
					'param'    => 'page_template',
					'operator' => '!=',
					'value'    => '_templates/_template-facetwp.php',
				),
			),
		),
		'menu_order'            => 50,
		'position'              => 'normal',
		'style'                 => 'default',
		'label_placement'       => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen'        => array(
			0 => 'permalink',
			1 => 'the_content',
			2 => 'custom_fields',
			3 => 'discussion',
			4 => 'comments',
			5 => 'format',
			6 => 'send-trackbacks',
		),
		'active'                => 1,
		'description'           => '',
	) );

endif;